using System.CommandLine;
using Albatross.CommandLine;
using Albatross.CommandLine.Annotations;
using EtlPipelines.Hosting;
using EtlPipelines.Samples.CsvToDatabase.AutoGenerated;
using EtlPipelines.Samples.Common;
using Microsoft.Extensions.DependencyInjection;

namespace EtlPipelines.Samples.CsvToDatabase;

/// <summary>The sample's own verb: write a file, then load it into SQLite.</summary>
[Verb<TradesHandler>(TradesPipeline.Name, Description = "Writes a CSV file, then loads it into a table in one transaction.")]
public class TradesParams
{
}

/// <summary>Handles the sample's verb.</summary>
public class TradesHandler : BaseHandler<TradesParams>
{
    private readonly TradesData _data;
    private readonly PipelineRunner _runner;

    public TradesHandler(ParseResult result, TradesParams parameters, TradesData data, PipelineRunner runner)
        : base(result, parameters)
    {
        ArgumentNullException.ThrowIfNull(data);
        ArgumentNullException.ThrowIfNull(runner);

        _data = data;
        _runner = runner;
    }

    public override async Task<int> InvokeAsync(CancellationToken cancellationToken)
    {
        await _data.WriteAsync(cancellationToken);
        await _data.CreateSqliteTableAsync(cancellationToken);

        return await _runner.RunAsync(TradesPipeline.Name, cancellationToken);
    }
}

/// <summary>
/// Builds the sample's command line application.
/// </summary>
/// <remarks>
/// A method rather than the body of <c>Program.cs</c> so that the tests can invoke the sample exactly
/// as a shell does — same verbs, same wiring, same exit code — instead of approximating it.
/// </remarks>
public static class TradesCli
{
    /// <summary>Runs the application and returns its exit code.</summary>
    public static Task<int> RunAsync(string[] args) =>
        new EtlPipelinesHost("A CSV file loaded into a database table, in one transaction.")
            .AddCommands(host => host.AddCommands())
            .UseSampleWorkspace(TradesPipeline.Name, (services, directory) =>
                services.RegisterCommands()
                    .AddSingleton<TradesData>()
                    .AddTradesPipeline(directory))
            .RunAsync(args);
}
