using System.CommandLine;
using Albatross.CommandLine;
using Albatross.CommandLine.Annotations;
using EtlPipelines.Hosting;
using EtlPipelines.Samples.SqlToWorkbook.AutoGenerated;
using EtlPipelines.Samples.Common;
using Microsoft.Extensions.DependencyInjection;

namespace EtlPipelines.Samples.SqlToWorkbook;

/// <summary>The sample's own verb: fill the database, then report on it.</summary>
[Verb<ReportHandler>(ReportPipeline.Name, Description = "Seeds a database, then builds a multi-sheet workbook from it.")]
public class ReportParams
{
}

/// <summary>Handles the sample's verb.</summary>
public class ReportHandler : BaseHandler<ReportParams>
{
    private readonly ReportData _data;
    private readonly PipelineRunner _runner;

    public ReportHandler(ParseResult result, ReportParams parameters, ReportData data, PipelineRunner runner)
        : base(result, parameters)
    {
        ArgumentNullException.ThrowIfNull(data);
        ArgumentNullException.ThrowIfNull(runner);

        _data = data;
        _runner = runner;
    }

    public override async Task<int> InvokeAsync(CancellationToken cancellationToken)
    {
        await _data.SeedAsync(cancellationToken);
        return await _runner.RunAsync(ReportPipeline.Name, cancellationToken);
    }
}

/// <summary>
/// Builds the sample's command line application.
/// </summary>
/// <remarks>
/// A method rather than the body of <c>Program.cs</c> so that the tests can invoke the sample exactly
/// as a shell does — same verbs, same wiring, same exit code — instead of approximating it.
/// </remarks>
public static class ReportCli
{
    /// <summary>Runs the application and returns its exit code.</summary>
    public static Task<int> RunAsync(string[] args) =>
        new EtlPipelinesHost("Several queries becoming the sheets of one workbook.")
            .UseSampleWorkspace()
            .AddCommands(host => host.AddCommands())
            .ConfigureServices((result, services) =>
            {
                // Built here rather than resolved: registering the pipeline needs the file paths, and
                // that happens while the container is still being composed. Everything else takes it
                // by injection.
                var workspace = SampleWorkspace.ForCommandLine(result, ReportPipeline.Name);

                services.RegisterCommands()
                    .AddSingleton(workspace)
                    .AddSingleton<ReportData>()
                    .AddReportPipeline(workspace);
            })
            .RunAsync(args);
}
