<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EtlPipelines.Samples.Branching</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtlPipelines.Core\EtlPipelines.Core.csproj" />
    <ProjectReference Include="..\EtlPipelines.Hosting\EtlPipelines.Hosting.csproj" />
    <ProjectReference Include="..\EtlPipelines.Csv\EtlPipelines.Csv.csproj" />
    <ProjectReference Include="..\EtlPipelines.Excel\EtlPipelines.Excel.csproj" />
  </ItemGroup>

</Project>
