using System.CommandLine;
using Albatross.CommandLine;
using Albatross.CommandLine.Annotations;
using EtlPipelines.Hosting;
using EtlPipelines.Samples.ExcelToSql.AutoGenerated;
using EtlPipelines.Samples.Common;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace EtlPipelines.Samples.ExcelToSql;

/// <summary>The sample's own verb: fill in a workbook, then load it.</summary>
[Verb<ImportHandler>(ImportPipeline.Name, Description = "Writes a hand-filled workbook, then loads it into a table.")]
public class ImportParams
{
}

/// <summary>Handles the sample's verb.</summary>
public class ImportHandler : BaseHandler<ImportParams>
{
    private readonly ImportData _data;
    private readonly RejectedRows _rejected;
    private readonly PipelineRunner _runner;
    private readonly ILogger<ImportHandler> _logger;

    public ImportHandler(
        ParseResult result,
        ImportParams parameters,
        ImportData data,
        RejectedRows rejected,
        PipelineRunner runner,
        ILogger<ImportHandler> logger)
        : base(result, parameters)
    {
        ArgumentNullException.ThrowIfNull(data);
        ArgumentNullException.ThrowIfNull(rejected);
        ArgumentNullException.ThrowIfNull(runner);
        ArgumentNullException.ThrowIfNull(logger);

        _data = data;
        _rejected = rejected;
        _runner = runner;
        _logger = logger;
    }

    public override async Task<int> InvokeAsync(CancellationToken cancellationToken)
    {
        await _data.PrepareAsync(cancellationToken);

        var exitCode = await _runner.RunAsync(ImportPipeline.Name, cancellationToken);

        // What the row counts do not say: how many rows the workbook held that nobody could read.
        _logger.LogInformation(
            "loaded {Loaded} rows, set aside {Rejected} that could not be read",
            await _data.CountAsync(cancellationToken),
            _rejected.Rows.Count);

        return exitCode;
    }
}

/// <summary>
/// Builds the sample's command line application.
/// </summary>
/// <remarks>
/// A method rather than the body of <c>Program.cs</c> so that the tests can invoke the sample exactly
/// as a shell does — same verbs, same wiring, same exit code — instead of approximating it.
/// </remarks>
public static class ImportCli
{
    /// <summary>Runs the application and returns its exit code.</summary>
    public static Task<int> RunAsync(string[] args) =>
        new EtlPipelinesHost("A hand-filled workbook loaded into a table, bad rows set aside.")
            .UseSampleWorkspace()
            .AddCommands(host => host.AddCommands())
            .ConfigureServices((result, services) =>
            {
                // Built here rather than resolved: registering the pipeline needs the file paths, and
                // that happens while the container is still being composed. Everything else takes it
                // by injection.
                var workspace = SampleWorkspace.ForCommandLine(result, ImportPipeline.Name);

                services.RegisterCommands()
                    .AddSingleton(workspace)
                    .AddSingleton<ImportData>()
                    .AddImportPipeline(workspace);
            })
            .RunAsync(args);
}
