<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EtlPipelines.Samples.CsvToExcel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtlPipelines.Core\EtlPipelines.Core.csproj" />
    <ProjectReference Include="..\EtlPipelines.Hosting\EtlPipelines.Hosting.csproj" />
    <ProjectReference Include="..\EtlPipelines.Extensions.Csv\EtlPipelines.Extensions.Csv.csproj" />
    <ProjectReference Include="..\EtlPipelines.Extensions.Excel\EtlPipelines.Extensions.Excel.csproj" />
  </ItemGroup>

</Project>
