using System.CommandLine;
using Albatross.CommandLine;
using Albatross.CommandLine.Annotations;
using EtlPipelines.Hosting;
using EtlPipelines.Samples.Branching.AutoGenerated;
using EtlPipelines.Samples.Common;
using Microsoft.Extensions.DependencyInjection;

namespace EtlPipelines.Samples.Branching;

/// <summary>The sample's own verb: write a feed, then archive and report from one pass over it.</summary>
[Verb<ReadingsHandler>(ReadingsPipeline.Name, Description = "Writes a sensor feed, then archives and reports it in one pass.")]
public class ReadingsParams
{
}

/// <summary>Handles the sample's verb.</summary>
public class ReadingsHandler : BaseHandler<ReadingsParams>
{
    private readonly ReadingsData _data;
    private readonly PipelineRunner _runner;

    public ReadingsHandler(ParseResult result, ReadingsParams parameters, ReadingsData data, PipelineRunner runner)
        : base(result, parameters)
    {
        ArgumentNullException.ThrowIfNull(data);
        ArgumentNullException.ThrowIfNull(runner);

        _data = data;
        _runner = runner;
    }

    public override async Task<int> InvokeAsync(CancellationToken cancellationToken)
    {
        await _data.WriteAsync(cancellationToken);
        return await _runner.RunAsync(ReadingsPipeline.Name, cancellationToken);
    }
}

/// <summary>
/// Builds the sample's command line application.
/// </summary>
/// <remarks>
/// A method rather than the body of <c>Program.cs</c> so that the tests can invoke the sample exactly
/// as a shell does — same verbs, same wiring, same exit code — instead of approximating it.
/// </remarks>
public static class ReadingsCli
{
    /// <summary>Runs the application and returns its exit code.</summary>
    public static Task<int> RunAsync(string[] args) =>
        new EtlPipelinesHost("One read of a source, an archive and a report out of it.")
            .AddCommands(host => host.AddCommands())
            .UseSampleWorkspace(ReadingsPipeline.Name, (services, directory) =>
                services.RegisterCommands()
                    .AddSingleton<ReadingsData>()
                    .AddReadingsPipeline(directory))
            .RunAsync(args);
}
