<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EtlPipelines.Samples.Branching</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samples.Common\Samples.Common.csproj" />
    <ProjectReference Include="..\..\src\EtlPipelines.Csv\EtlPipelines.Csv.csproj" />
    <ProjectReference Include="..\..\src\EtlPipelines.Excel\EtlPipelines.Excel.csproj" />
  </ItemGroup>

</Project>
