<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.TestingHelpers" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EtlPipelines.Csv\EtlPipelines.Csv.csproj" />
    <ProjectReference Include="..\..\src\EtlPipelines\EtlPipelines.csproj" />
  </ItemGroup>

</Project>
