using System.CommandLine;
using System.IO.Abstractions;
using Albatross.CommandLine;
using EtlPipelines.GrpcClient;
using EtlPipelines.Hosting.AutoGenerated;
using EtlPipelines.PipelineExecution.V1;
using Grpc.Net.Client;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace EtlPipelines.Hosting;

/// <summary>
/// Turns an application that registers pipelines into a command line one.
/// </summary>
/// <remarks>
/// <para>
/// Wraps <see cref="CommandHost"/> with the pieces every pipeline application wants and none of them
/// should have to assemble: a generic host, console logging, a listener that surfaces the runtime's
/// own traces, and the <c>run</c> and <c>list</c> verbs. Registering a pipeline is then the only
/// thing an application has to do to become runnable:
/// </para>
/// <code>
/// return await new EtlPipelinesHost("sales")
///     .ConfigureServices(services => services.AddEtlPipeline("orders", builder => ...))
///     .RunAsync(args);
/// </code>
/// <para>
/// Commands of your own go in alongside the built-in ones. Declare them with
/// <c>[Verb&lt;THandler&gt;("name")]</c>, then hand over the two methods the source generator wrote
/// into your assembly's <c>AutoGenerated</c> namespace — <c>RegisterCommands</c> through
/// <see cref="ConfigureServices(Action{IServiceCollection})"/> and <c>AddCommands</c> through
/// <see cref="AddCommands"/>. A
/// handler is resolved from the container, so it can take whatever it needs, <see cref="PipelineRunner"/>
/// included.
/// </para>
/// <para>
/// <see cref="SessionIdOption"/>/<see cref="ServerUrlOption"/> are built in too (SERVER.md Phase
/// 6): given both, this run pulls its configuration from and reports its progress to the named
/// <c>EtlPipelines.Server</c> - no separate opt-in, since every application built on this host
/// already carries that capability. Neither given (every application still works exactly as
/// before this existed) skips both.
/// </para>
/// </remarks>
public sealed class EtlPipelinesHost
{
    private readonly CommandHost _host;
    private IDirectoryInfo? _workspace;

    /// <summary>Starts an application whose root command is described by <paramref name="description"/>.</summary>
    public EtlPipelinesHost(string description)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(description);

        _host = new CommandHost(description);

        _host.RegisterServices((result, services) =>
        {
            services.TryAddSingleton(FileSystem);
            services.TryAddSingleton<PipelineRunner>();
            services.TryAddSingleton<PipelineTraceLogger>();
            services.RegisterCommands();
            services.AddKeyedSingleton(WorkspaceKey, GetWorkspace(result));

            RegisterGrpcClient(result, services);
        });

        // On the root command and recursive, so they reach every verb and show up in --help. Both
        // have to be read from the parse result rather than injected: logging is configured, and the
        // workspace directory created, while the host is being built, long before any handler could
        // ask for either.
        _host.CommandBuilder.RootCommand.Add(VerboseOption);
        _host.CommandBuilder.RootCommand.Add(WorkDirOption);

        // Same reasoning: every application built on this host gets --session-id/--server-url
        // built in (SERVER.md Phase 6) rather than as a separate opt-in a sample's own Program.cs
        // has to ask for - see RegisterGrpcClient/ConfigureGrpcConfiguration below.
        _host.CommandBuilder.RootCommand.Add(SessionIdOption);
        _host.CommandBuilder.RootCommand.Add(ServerUrlOption);

        // Resolving the listener is what starts it, and this runs before any command does.
        _host.ConfigureApplication((_, services) => services.GetRequiredService<PipelineTraceLogger>());

        // Same contract as PipelineTraceLogger above - GetService, not GetRequiredService, since
        // GrpcProgressReporter is only actually registered (RegisterGrpcClient above) when both
        // options were given on the command line; resolving it here is what starts it listening.
        _host.ConfigureApplication((_, services) => services.GetService<GrpcProgressReporter>());
    }

    /// <summary>
    /// Turns the log level down to <see cref="LogLevel.Debug"/>, which is where the runtime's own
    /// traces are written.
    /// </summary>
    public static Option<bool> VerboseOption { get; } = new("--verbose", "-v")
    {
        Description = "Log at debug level, which includes the pipeline's own per-stage traces.",
        Recursive = true,
    };

    /// <summary>The directory an application reads from and writes into, unless told otherwise.</summary>
    public static Option<string?> WorkDirOption { get; } = new("--work-dir")
    {
        Description = "Directory to read and write in. Defaults to a new directory under the temp path.",
        Recursive = true,
    };

    /// <summary>The run-scoped session id the server issued for this run - mirrors <c>Runs.Id</c> (SERVER.md Phase 3).</summary>
    public static Option<string?> SessionIdOption { get; } = new("--session-id")
    {
        Description = "The run-scoped session id issued by the server for this run. Together with " +
            "--server-url, turns on gRPC-backed configuration pull and progress reporting; omit both for a plain local run.",
        Recursive = true,
    };

    /// <summary>The <c>EtlPipelines.Server</c> gRPC endpoint this run reports progress to and pulls configuration from.</summary>
    public static Option<string?> ServerUrlOption { get; } = new("--server-url")
    {
        Description = "The EtlPipelines.Server gRPC endpoint this run reports progress to and pulls configuration from.",
        Recursive = true,
    };

    /// <summary>The key the working directory registers is resolved under.</summary>
    /// <remarks>
    /// A constant rather than a type of its own: the directory is an <see cref="IDirectoryInfo"/>,
    /// which is far too general to register unkeyed — something else registering one of its own would
    /// silently take over. Resolve it with <c>[FromKeyedServices(EtlPipelinesHost.WorkspaceKey)]</c>.
    /// </remarks>
    public const string WorkspaceKey = "workspace";

    /// <summary>
    /// The filesystem this host registers as <see cref="IFileSystem"/>.
    /// </summary>
    /// <remarks>
    /// Exposed because composing a pipeline needs it before there is a container to resolve it from:
    /// the file connectors take an <see cref="IFileInfo"/>, and that has to exist while
    /// <c>AddEtlPipeline</c> is running. Using this rather than a <c>new FileSystem()</c> of your own
    /// keeps the one the application composes against and the one it later resolves the same object.
    /// <para>
    /// Registered with <c>TryAddSingleton</c>, so an application that registers its own — a
    /// <c>MockFileSystem</c> in a test, say — keeps it.
    /// </para>
    /// </remarks>
    public IFileSystem FileSystem { get; } = new FileSystem();

    /// <summary>Registers the application's services — its pipelines, and its commands' dependencies.</summary>
    public EtlPipelinesHost ConfigureServices(Action<IServiceCollection> configure)
    {
        ArgumentNullException.ThrowIfNull(configure);

        _host.RegisterServices((_, services) => configure(services));
        return this;
    }

    /// <summary>Registers the application's services, with the parsed command line to hand.</summary>
    public EtlPipelinesHost ConfigureServices(Action<ParseResult, IServiceCollection> configure)
    {
        ArgumentNullException.ThrowIfNull(configure);

        _host.RegisterServices(configure);
        return this;
    }
    
    /// <summary>Registers the application's services, with the parsed command line to hand.</summary>
    public EtlPipelinesHost ConfigureServices(Action<ParseResult, IServiceCollection, IDirectoryInfo> configure)
    {
        ArgumentNullException.ThrowIfNull(configure);

        _host.RegisterServices((result, services) => configure(result, services, GetWorkspace(result)));
        return this;
    }
    
    private IDirectoryInfo GetWorkspace(ParseResult result)
    {
        if( _workspace is not null)
            return _workspace;
        
        var path = result.GetValue(WorkDirOption);
        var directory = path is not null
            ? FileSystem.DirectoryInfo.New(path)
            : FileSystem.Directory.CreateTempSubdirectory($"etl-workspace-{Guid.NewGuid():N}");
        
        directory.Create();
        
        return _workspace = directory;
    }

    /// <summary>Reaches the underlying generic host, for configuration and logging.</summary>
    public EtlPipelinesHost ConfigureHost(Action<IHostBuilder> configure)
    {
        ArgumentNullException.ThrowIfNull(configure);

        _host.ConfigureHost(configure);
        return this;
    }

    /// <summary>
    /// Adds the application's own commands to the tree.
    /// </summary>
    /// <remarks>
    /// Pass the generated extension: <c>host =&gt; host.AddCommands()</c>, having imported your
    /// assembly's <c>AutoGenerated</c> namespace. It has to happen here rather than through
    /// <see cref="ConfigureServices(Action{IServiceCollection})"/> because the tree is what the
    /// arguments are parsed against.
    /// </remarks>
    public EtlPipelinesHost AddCommands(Action<CommandHost> add)
    {
        ArgumentNullException.ThrowIfNull(add);

        add(_host);
        return this;
    }

    /// <summary>Parses <paramref name="args"/>, runs the command they name, and returns its exit code.</summary>
    public async Task<int> RunAsync(string[] args)
    {
        ArgumentNullException.ThrowIfNull(args);

        // The built-in verbs go on last so that an application naming a command the same thing gets
        // to define it; adding ours first would make the duplicate the error instead.
        _host.AddCommands();

        // An application built on this host exists to run its pipelines, so being asked for nothing
        // in particular is taken as being asked for all of them rather than for the help text.
        _host.Parse(args.Length == 0 ? ["run"] : args);

        // After parsing, because --verbose is read from the result and the overload that hands it
        // over throws until there is one.
        ConfigureLogging();

        // Same reason - reads --session-id/--server-url off the parse result.
        ConfigureGrpcConfiguration();

        await using var host = _host.Build();
        return await host.InvokeAsync().ConfigureAwait(false);
    }

    /// <summary>
    /// Registers the typed <c>PipelineExecutionServiceClient</c> and <see cref="GrpcProgressReporter"/>
    /// when <see cref="SessionIdOption"/>/<see cref="ServerUrlOption"/> were both given - a plain
    /// local run (neither given, which every sample still works as before this existed) registers
    /// neither, so <see cref="GrpcProgressReporter"/> is never resolved and never starts listening.
    /// </summary>
    private static void RegisterGrpcClient(ParseResult result, IServiceCollection services)
    {
        var (sessionId, serverUrl) = SessionOf(result);
        if (sessionId is null || serverUrl is null)
        {
            return;
        }

        // Cleartext HTTP/2 (h2c) - no TLS anywhere in this phase (SERVER.md's "Auth/authz:
        // deferred entirely"), so every client that dials Server has to opt into h2c itself, the
        // same switch EtlPipelines.Agent.GrpcClient.AddAgentGrpcClient sets for the agent's own
        // connection.
        AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

        services.AddGrpcClient<PipelineExecutionService.PipelineExecutionServiceClient>(
            options => options.Address = new Uri(serverUrl));

        services.AddSingleton(provider => new GrpcProgressReporter(
            provider.GetRequiredService<PipelineExecutionService.PipelineExecutionServiceClient>(),
            sessionId,
            provider.GetRequiredService<ILogger<GrpcProgressReporter>>()));
    }

    /// <summary>
    /// Adds <see cref="GrpcConfigurationSource"/> to app configuration when
    /// <see cref="SessionIdOption"/>/<see cref="ServerUrlOption"/> were both given - called from
    /// <see cref="RunAsync"/> itself, after <c>Parse(args)</c>, the same placement
    /// <see cref="ConfigureLogging"/> already relies on to read <see cref="VerboseOption"/> safely.
    /// </summary>
    private void ConfigureGrpcConfiguration()
    {
        var (sessionId, serverUrl) = SessionOf(_host.RequiredResult);
        if (sessionId is null || serverUrl is null)
        {
            return;
        }

        _host.ConfigureHost(builder => builder.ConfigureAppConfiguration((_, configBuilder) =>
        {
            // A short-lived channel/client of its own, not the one RegisterGrpcClient registers
            // above - this runs during IHostBuilder.Build()'s app-configuration phase, before the
            // container that would otherwise hand one over even exists.
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
            var channel = GrpcChannel.ForAddress(serverUrl);
            var client = new PipelineExecutionService.PipelineExecutionServiceClient(channel);
            configBuilder.Add(new GrpcConfigurationSource(client, sessionId));
        }));
    }

    private static (string? SessionId, string? ServerUrl) SessionOf(ParseResult result)
    {
        var sessionId = result.GetValue(SessionIdOption);
        var serverUrl = result.GetValue(ServerUrlOption);

        return string.IsNullOrEmpty(sessionId) || string.IsNullOrEmpty(serverUrl)
            ? (null, null)
            : (sessionId, serverUrl);
    }

    private void ConfigureLogging() =>
        _host.ConfigureHost((result, builder) => builder.ConfigureLogging(logging =>
        {
            logging.ClearProviders();
            logging.AddSimpleConsole(options =>
            {
                options.SingleLine = true;
                options.TimestampFormat = "HH:mm:ss ";
            });

            if (result.GetValue(VerboseOption))
            {
                logging.SetMinimumLevel(LogLevel.Debug);
            }

            // The command line plumbing narrating itself - "Invoking command", "Disposing" - says
            // nothing about the pipeline, which is the only thing anyone runs this to watch. After
            // the level above, so that --verbose does not turn it back on.
            logging.AddFilter("Albatross.CommandLine", LogLevel.Warning);
        }));
}
