using System.CommandLine;
using Albatross.CommandLine;
using EtlPipelines.Hosting.AutoGenerated;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace EtlPipelines.Hosting;

/// <summary>
/// Turns an application that registers pipelines into a command line one.
/// </summary>
/// <remarks>
/// <para>
/// Wraps <see cref="CommandHost"/> with the pieces every pipeline application wants and none of them
/// should have to assemble: a generic host, console logging, a listener that surfaces the runtime's
/// own traces, and the <c>run</c> and <c>list</c> verbs. Registering a pipeline is then the only
/// thing an application has to do to become runnable:
/// </para>
/// <code>
/// return await new EtlPipelinesHost("sales")
///     .ConfigureServices(services => services.AddEtlPipeline("orders", builder => ...))
///     .RunAsync(args);
/// </code>
/// <para>
/// Commands of your own go in alongside the built-in ones. Declare them with
/// <c>[Verb&lt;THandler&gt;("name")]</c>, then hand over the two methods the source generator wrote
/// into your assembly's <c>AutoGenerated</c> namespace — <c>RegisterCommands</c> through
/// <see cref="ConfigureServices(Action{IServiceCollection})"/> and <c>AddCommands</c> through
/// <see cref="AddCommands"/>. A
/// handler is resolved from the container, so it can take whatever it needs, <see cref="PipelineRunner"/>
/// included.
/// </para>
/// </remarks>
public sealed class EtlPipelinesHost
{
    private readonly CommandHost _host;

    /// <summary>Starts an application whose root command is described by <paramref name="description"/>.</summary>
    public EtlPipelinesHost(string description)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(description);

        _host = new CommandHost(description);

        _host.RegisterServices((_, services) =>
        {
            services.TryAddSingleton<PipelineRunner>();
            services.TryAddSingleton<PipelineTraceLogger>();
            services.RegisterCommands();
        });

        _host.ConfigureHost(builder => builder.ConfigureLogging(logging =>
        {
            logging.ClearProviders();
            logging.AddSimpleConsole(options =>
            {
                options.SingleLine = true;
                options.TimestampFormat = "HH:mm:ss ";
            });

            // The command line plumbing narrating itself - "Invoking command", "Disposing" - says
            // nothing about the pipeline, which is the only thing anyone runs this to watch.
            logging.AddFilter("Albatross.CommandLine", LogLevel.Warning);
        }));

        // Resolving the listener is what starts it, and this runs before any command does.
        _host.ConfigureApplication((_, services) => services.GetRequiredService<PipelineTraceLogger>());
    }

    /// <summary>Registers the application's services — its pipelines, and its commands' dependencies.</summary>
    public EtlPipelinesHost ConfigureServices(Action<IServiceCollection> configure)
    {
        ArgumentNullException.ThrowIfNull(configure);

        _host.RegisterServices((_, services) => configure(services));
        return this;
    }

    /// <summary>Registers the application's services, with the parsed command line to hand.</summary>
    public EtlPipelinesHost ConfigureServices(Action<ParseResult, IServiceCollection> configure)
    {
        ArgumentNullException.ThrowIfNull(configure);

        _host.RegisterServices(configure);
        return this;
    }

    /// <summary>Reaches the underlying generic host, for configuration and logging.</summary>
    public EtlPipelinesHost ConfigureHost(Action<IHostBuilder> configure)
    {
        ArgumentNullException.ThrowIfNull(configure);

        _host.ConfigureHost(configure);
        return this;
    }

    /// <summary>
    /// Adds the application's own commands to the tree.
    /// </summary>
    /// <remarks>
    /// Pass the generated extension: <c>host =&gt; host.AddCommands()</c>, having imported your
    /// assembly's <c>AutoGenerated</c> namespace. It has to happen here rather than through
    /// <see cref="ConfigureServices(Action{IServiceCollection})"/> because the tree is what the
    /// arguments are parsed against.
    /// </remarks>
    public EtlPipelinesHost AddCommands(Action<CommandHost> add)
    {
        ArgumentNullException.ThrowIfNull(add);

        add(_host);
        return this;
    }

    /// <summary>Parses <paramref name="args"/>, runs the command they name, and returns its exit code.</summary>
    public async Task<int> RunAsync(string[] args)
    {
        ArgumentNullException.ThrowIfNull(args);

        // The built-in verbs go on last so that an application naming a command the same thing gets
        // to define it; adding ours first would make the duplicate the error instead.
        _host.AddCommands();

        await using var host = _host.Parse(args).Build();
        return await host.InvokeAsync().ConfigureAwait(false);
    }
}
