using System.CommandLine;
using Albatross.CommandLine;
using Albatross.CommandLine.Annotations;
using EtlPipelines.Hosting;
using EtlPipelines.Samples.CsvToExcel.AutoGenerated;
using EtlPipelines.Samples.Common;
using Microsoft.Extensions.DependencyInjection;

namespace EtlPipelines.Samples.CsvToExcel;

/// <summary>The sample's own verb: put the input in place, then run the pipeline over it.</summary>
[Verb<SalesHandler>(SalesPipeline.Name, Description = "Writes an input file, then runs the sales pipeline over it.")]
public class SalesParams
{
}

/// <summary>
/// Handles the sample's verb.
/// </summary>
/// <remarks>
/// A demonstration of adding a command alongside the built-in <c>run</c> and <c>list</c>: the handler
/// is resolved from the container, so it takes the seeder and the runner rather than building either.
/// </remarks>
public class SalesHandler : BaseHandler<SalesParams>
{
    private readonly SalesData _data;
    private readonly PipelineRunner _runner;

    public SalesHandler(ParseResult result, SalesParams parameters, SalesData data, PipelineRunner runner)
        : base(result, parameters)
    {
        ArgumentNullException.ThrowIfNull(data);
        ArgumentNullException.ThrowIfNull(runner);

        _data = data;
        _runner = runner;
    }

    public override async Task<int> InvokeAsync(CancellationToken cancellationToken)
    {
        await _data.WriteAsync(cancellationToken);
        return await _runner.RunAsync(SalesPipeline.Name, cancellationToken);
    }
}

/// <summary>
/// Builds the sample's command line application.
/// </summary>
/// <remarks>
/// A method rather than the body of <c>Program.cs</c> so that the tests can invoke the sample exactly
/// as a shell does — same verbs, same wiring, same exit code — instead of approximating it.
/// </remarks>
public static class SalesCli
{
    /// <summary>Runs the application and returns its exit code.</summary>
    public static Task<int> RunAsync(string[] args) =>
        new EtlPipelinesHost("A CSV file filtered and reshaped into a workbook.")
            .AddCommands(host => host.AddCommands())
            .UseSampleWorkspace(SalesPipeline.Name, (services, directory) =>
                services.RegisterCommands()
                    .AddSingleton<SalesData>()
                    .AddSalesPipeline(directory))
            .RunAsync(args);
}
